"""add preparation activity tracking

Revision ID: 01429bf88879
Revises: cba6fd8abb1b
Create Date: 2026-08-17 03:05:25.247889

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01429bf88879'
down_revision: str | Sequence[str] | None = 'cba6fd8abb1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preparation_activities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('activity_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_preparation_activities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preparation_activities')),
    sa.UniqueConstraint('user_id', 'activity_type', 'source_id', name='uq_preparation_activity_source')
    )
    op.create_index(op.f('ix_preparation_activities_module'), 'preparation_activities', ['module'], unique=False)
    op.create_index(op.f('ix_preparation_activities_source_id'), 'preparation_activities', ['source_id'], unique=False)
    op.create_index(op.f('ix_preparation_activities_user_id'), 'preparation_activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preparation_activities_user_id'), table_name='preparation_activities')
    op.drop_index(op.f('ix_preparation_activities_source_id'), table_name='preparation_activities')
    op.drop_index(op.f('ix_preparation_activities_module'), table_name='preparation_activities')
    op.drop_table('preparation_activities')
    # ### end Alembic commands ###
