"""add coding submissions

Revision ID: 0d723fec0a2a
Revises: 2440106aaf7d
Create Date: 2026-08-21 17:37:33.120769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d723fec0a2a'
down_revision: Union[str, Sequence[str], None] = '2440106aaf7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_submissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('hidden_passed', sa.Integer(), nullable=False),
    sa.Column('hidden_total', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('all_passed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['coding_questions.id'], name=op.f('fk_coding_submissions_question_id_coding_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coding_submissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coding_submissions'))
    )
    op.create_index(op.f('ix_coding_submissions_all_passed'), 'coding_submissions', ['all_passed'], unique=False)
    op.create_index(op.f('ix_coding_submissions_question_id'), 'coding_submissions', ['question_id'], unique=False)
    op.create_index(op.f('ix_coding_submissions_user_id'), 'coding_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coding_submissions_user_id'), table_name='coding_submissions')
    op.drop_index(op.f('ix_coding_submissions_question_id'), table_name='coding_submissions')
    op.drop_index(op.f('ix_coding_submissions_all_passed'), table_name='coding_submissions')
    op.drop_table('coding_submissions')
    # ### end Alembic commands ###
