"""add coding question bank

Revision ID: 2440106aaf7d
Revises: 01429bf88879
Create Date: 2026-08-17 05:19:06.749296

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2440106aaf7d'
down_revision: str | Sequence[str] | None = '01429bf88879'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_questions',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('input_format', sa.Text(), nullable=False),
    sa.Column('output_format', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coding_questions'))
    )
    op.create_index(op.f('ix_coding_questions_difficulty'), 'coding_questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_coding_questions_slug'), 'coding_questions', ['slug'], unique=True)
    op.create_index(op.f('ix_coding_questions_topic'), 'coding_questions', ['topic'], unique=False)
    op.create_table('coding_test_cases',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['coding_questions.id'], name=op.f('fk_coding_test_cases_question_id_coding_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coding_test_cases')),
    sa.UniqueConstraint('question_id', 'position', name='uq_coding_test_cases_question_position')
    )
    op.create_index(op.f('ix_coding_test_cases_question_id'), 'coding_test_cases', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coding_test_cases_question_id'), table_name='coding_test_cases')
    op.drop_table('coding_test_cases')
    op.drop_index(op.f('ix_coding_questions_topic'), table_name='coding_questions')
    op.drop_index(op.f('ix_coding_questions_slug'), table_name='coding_questions')
    op.drop_index(op.f('ix_coding_questions_difficulty'), table_name='coding_questions')
    op.drop_table('coding_questions')
    # ### end Alembic commands ###
