"""add coding submissions

Revision ID: 37362572a2a6
Revises: 0d723fec0a2a
Create Date: 2026-09-05 17:37:11.158560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37362572a2a6'
down_revision: Union[str, Sequence[str], None] = '0d723fec0a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coding_submissions_all_passed'), table_name='coding_submissions')
    op.drop_column('coding_submissions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coding_submissions', sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_coding_submissions_all_passed'), 'coding_submissions', ['all_passed'], unique=False)
    # ### end Alembic commands ###
