"""actually add resume analyses table

Revision ID: 4c8ec7504734
Revises: 4844f59f87bd
Create Date: 2026-09-23 05:42:42.992424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8ec7504734'
down_revision: Union[str, Sequence[str], None] = '4844f59f87bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_analyses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('target_role', sa.String(length=120), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('missing_keywords', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('improved_summary', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resume_analyses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_analyses'))
    )
    op.create_index(op.f('ix_resume_analyses_user_id'), 'resume_analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_analyses_user_id'), table_name='resume_analyses')
    op.drop_table('resume_analyses')
    # ### end Alembic commands ###

