"""create student profiles

Revision ID: 98764d72afc8
Revises: b8074f34dee7
Create Date: 2026-08-09 18:15:06.516269

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '98764d72afc8'
down_revision: str | Sequence[str] | None = 'b8074f34dee7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('college_name', sa.String(length=180), nullable=False),
    sa.Column('degree', sa.String(length=120), nullable=False),
    sa.Column('branch', sa.String(length=120), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('target_companies', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weak_areas', sa.JSON(), nullable=False),
    sa.Column('preparation_goals', sa.JSON(), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_student_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_profiles'))
    )
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
