"""add student profiles

Revision ID: b8074f34dee7
Revises: b64f126d0dd0
Create Date: 2026-08-09 17:55:30.914863

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'b8074f34dee7'
down_revision: str | Sequence[str] | None = 'b64f126d0dd0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
