"""add aptitude practice

Revision ID: cba6fd8abb1b
Revises: 98764d72afc8
Create Date: 2026-08-17 00:25:10.363936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba6fd8abb1b'
down_revision: Union[str, Sequence[str], None] = '98764d72afc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aptitude_questions',
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aptitude_questions'))
    )
    op.create_index(op.f('ix_aptitude_questions_category'), 'aptitude_questions', ['category'], unique=False)
    op.create_index(op.f('ix_aptitude_questions_difficulty'), 'aptitude_questions', ['difficulty'], unique=False)
    op.create_table('aptitude_attempts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('score_percent', sa.Float(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_aptitude_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aptitude_attempts'))
    )
    op.create_index(op.f('ix_aptitude_attempts_user_id'), 'aptitude_attempts', ['user_id'], unique=False)
    op.create_table('aptitude_answers',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['aptitude_attempts.id'], name=op.f('fk_aptitude_answers_attempt_id_aptitude_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['aptitude_questions.id'], name=op.f('fk_aptitude_answers_question_id_aptitude_questions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aptitude_answers')),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_aptitude_answers_attempt_question')
    )
    op.create_index(op.f('ix_aptitude_answers_attempt_id'), 'aptitude_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_aptitude_answers_question_id'), 'aptitude_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aptitude_answers_question_id'), table_name='aptitude_answers')
    op.drop_index(op.f('ix_aptitude_answers_attempt_id'), table_name='aptitude_answers')
    op.drop_table('aptitude_answers')
    op.drop_index(op.f('ix_aptitude_attempts_user_id'), table_name='aptitude_attempts')
    op.drop_table('aptitude_attempts')
    op.drop_index(op.f('ix_aptitude_questions_difficulty'), table_name='aptitude_questions')
    op.drop_index(op.f('ix_aptitude_questions_category'), table_name='aptitude_questions')
    op.drop_table('aptitude_questions')
    # ### end Alembic commands ###
